import { DocCallout } from '@/components/DocCallout';
import { DocCode } from '@/components/DocCode';

const Method = ({ verb, path, desc }: { verb: string; path: string; desc: string }) => {
  const colors: Record<string, string> = {
    GET: 'text-accent-success bg-accent-success/10',
    POST: 'text-accent-primary bg-accent-primary/10',
    DELETE: 'text-accent-danger bg-accent-danger/10',
  };
  return (
    <div className="glass-card rounded-xl px-4 py-3 mb-3">
      <div className="flex items-center gap-2 mb-1">
        <span className={`text-xs font-bold font-mono px-2 py-0.5 rounded ${colors[verb] ?? 'text-text-muted'}`}>
          {verb}
        </span>
        <code className="text-sm text-text-primary">{path}</code>
      </div>
      <p className="text-text-muted text-sm">{desc}</p>
    </div>
  );
};

const Field = ({ name, type, req, desc }: { name: string; type: string; req?: boolean; desc: string }) => (
  <tr>
    <td>
      <code style={{ color: 'var(--accent-primary)' }} className="text-xs">{name}</code>
      {req && <span className="ml-1 text-accent-danger text-xs">*</span>}
    </td>
    <td><code className="text-xs text-text-muted">{type}</code></td>
    <td className="text-text-muted text-sm">{desc}</td>
  </tr>
);

export default function ApiPage() {
  return (
    <article className="prose-docs">
      <h1>API Reference</h1>
      <p className="lead">
        The gateway exposes a REST API over HTTP. All endpoints require an API key passed as a
        header. All request and response bodies are JSON.
      </p>

      <hr />

      <h2>Authentication</h2>
      <p>Every request must include your API key:</p>
      <DocCode language="http">{`X-API-KEY: your-api-key`}</DocCode>
      <p>
        Requests without a valid key return <code>401 Unauthorized</code>. Rate limiting returns{' '}
        <code>429 Too Many Requests</code> — the SDK handles retries automatically.
      </p>

      <DocCallout type="note">
        The <code>/health</code> endpoint does not require authentication. Use it for uptime
        monitoring without exposing your API key.
      </DocCallout>

      <hr />

      <h2>Base URL</h2>
      <DocCode language="bash">{`https://your-gateway.up.railway.app`}</DocCode>
      <p>All paths below are relative to this base.</p>

      <hr />

      <h2>Intents</h2>
      <div className="not-prose">
        <Method verb="POST" path="/v1/intents" desc="Submit a new encrypted intent to the gateway." />
        <Method verb="GET" path="/v1/intents" desc="List intents. Filter by user address, status, or batch ID." />
        <Method verb="GET" path="/v1/intents/:intentId" desc="Get the current status of a single intent." />
        <Method verb="POST" path="/v1/intents/:intentId/cancel" desc="Cancel an intent. Requires wallet signature." />
        <Method verb="POST" path="/v1/intents/:intentId/onchain" desc="Notify the gateway that a wallet transaction confirmed on-chain." />
      </div>

      <h3>POST /v1/intents — request body</h3>
      <table>
        <thead>
          <tr><th>Field</th><th>Type</th><th>Description</th></tr>
        </thead>
        <tbody>
          <Field name="intent_id" type="string" req desc="Unique ID generated by IntentBuilder" />
          <Field name="user_address" type="string" req desc="Starknet address of the user placing the order" />
          <Field name="ciphertext" type="string" req desc="Hex-encoded AES-GCM encrypted intent payload" />
          <Field name="encrypted_session_key" type="string" req desc="Session key encrypted with the gateway's public key" />
          <Field name="client_public_key" type="string" req desc="Client's X25519 ephemeral public key (hex)" />
          <Field name="commitment" type="string" req desc="Pedersen hash of the full intent — what goes on-chain" />
          <Field name="user_signature" type="string[]" req desc="Starknet signature components from the user's wallet" />
          <Field name="nonce" type="string" req desc="Random nonce used in intent hash and amount commitment" />
          <Field name="authorization_hash" type="string" desc="Optional: hash the user explicitly authorised off-chain" />
          <Field name="submission_mode" type="string" desc="'GATEWAY' (default) or 'SELF_COMMIT' — who submits the on-chain tx" />
        </tbody>
      </table>

      <h3>POST /v1/intents — response</h3>
      <DocCode language="json">{`{
  "intent_id": "0x...",
  "batch_id": "0x...",
  "estimated_execution_time": 28,
  "awaiting_user_transaction": true
}`}</DocCode>

      <h3>GET /v1/intents — query params</h3>
      <table>
        <thead>
          <tr><th>Param</th><th>Type</th><th>Description</th></tr>
        </thead>
        <tbody>
          <Field name="user_address" type="string" desc="Filter to a specific wallet address" />
          <Field name="status" type="string" desc="pending | committed | in_batch | settled | failed | cancelled | expired" />
          <Field name="batch_id" type="string" desc="Filter to intents in a specific batch" />
          <Field name="limit" type="number" desc="Max results per page (default 20, max 100)" />
          <Field name="offset" type="number" desc="Pagination offset" />
        </tbody>
      </table>

      <hr />

      <h2>Batches</h2>
      <div className="not-prose">
        <Method verb="GET" path="/v1/batches" desc="List batch windows. Filter by status." />
        <Method verb="GET" path="/v1/batches/:batchId" desc="Get details of a single batch." />
        <Method verb="GET" path="/v1/batches/:batchId/intents" desc="List all intent IDs in a batch." />
      </div>

      <h3>Batch object</h3>
      <DocCode language="json">{`{
  "batch_id": "0x...",
  "close_time": 1700000030,
  "intent_count": 4,
  "auction_deadline": 1700000050,
  "status": "settled",
  "created_at": "2024-01-01T00:00:00Z",
  "settled_at": "2024-01-01T00:00:55Z",
  "failure_reason": null,
  "failed_at": null
}`}</DocCode>

      <hr />

      <h2>Gateway</h2>
      <div className="not-prose">
        <Method verb="GET" path="/v1/gateway/public_key" desc="Returns the gateway's current X25519 public key. Fetch this before encrypting an intent." />
        <Method verb="GET" path="/health" desc="Returns 200 if the gateway is up. No auth required." />
      </div>

      <h3>GET /v1/gateway/public_key — response</h3>
      <DocCode language="json">{`{
  "gateway_public_key": "0x..."
}`}</DocCode>

      <hr />

      <h2>Error format</h2>
      <p>All errors return a consistent JSON body:</p>
      <DocCode language="json">{`{
  "error": "intent_not_found",
  "message": "No intent with that ID exists"
}`}</DocCode>
      <p>Common status codes:</p>
      <table>
        <thead>
          <tr><th>Code</th><th>Meaning</th></tr>
        </thead>
        <tbody>
          <tr><td><code>400</code></td><td>Bad request — malformed body or invalid field</td></tr>
          <tr><td><code>401</code></td><td>Missing or invalid API key</td></tr>
          <tr><td><code>404</code></td><td>Resource not found</td></tr>
          <tr><td><code>409</code></td><td>Conflict — intent already exists with that ID</td></tr>
          <tr><td><code>429</code></td><td>Rate limited — back off and retry</td></tr>
          <tr><td><code>500</code></td><td>Gateway error — check logs</td></tr>
        </tbody>
      </table>
    </article>
  );
}
